// <auto-generated />
namespace QueueSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HeThongSo_Alter_STTOnline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HeThongSo_Alter_STTOnline));
        
        string IMigrationMetadata.Id
        {
            get { return "201608240432232_HeThongSo_Alter_STTOnline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
